apiVersion: v1
kind: PersistentVolume
metadata:
  name: nfs-pv
  labels:
    nfs: storage
spec:
  persistentVolumeReclaimPolicy: Retain
  capacity:
    storage: 20G
  accessModes:
    - ReadWriteMany
  nfs:
    server: 192.168.3.85
    path: "/var/nfsshare"
