apiVersion: v1
kind: PersistentVolume
metadata:
  name: nfs-storage
  labels:
    nfs: volume
spec:
  persistentVolumeReclaimPolicy: Recycle
  storageClassName: storage
  capacity:
    storage: 20G
  accessModes:
    - ReadWriteMany
  nfs:
    server: 192.168.3.85
    path: "/var/nfsshare"
