apiVersion: v1
kind: Pod
metadata:
  name: fscoding-centos
  labels:
    app: example
spec:
  containers:
  - image: centos
    name: fscoding
    volumeMounts:
    - mountPath: /tmp
      name: test-volume
    stdin: true
    tty: true
  nodeSelector:
    kubernetes.io/hostname: node-2
  volumes:
    
    - name: test-volume
      persistentVolumeClaim:
        claimName: nfs-pvc
